"""empty message

Revision ID: 1ae37dcf8153
Revises: 984dc1192790
Create Date: 2021-06-24 14:18:29.463542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae37dcf8153'
down_revision = '984dc1192790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hospital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('who', sa.String(), nullable=True),
    sa.Column('passphrase', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('HospitalDB')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('HospitalDB',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"HospitalDB_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('who', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passphrase', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='HospitalDB_pkey')
    )
    op.drop_table('hospital')
    # ### end Alembic commands ###
