"""empty message

Revision ID: 9ae2e4b937af
Revises: 1ae37dcf8153
Create Date: 2021-06-24 14:26:55.911128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ae2e4b937af'
down_revision = '1ae37dcf8153'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hospital', 'passphrase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hospital', sa.Column('passphrase', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
